# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b49be7cf85200d2476ea27a203ef34eb8eec282f45fb89f6300440412c43dc4edb6a185bfa631a7a551a95a9bb645986bfff1065252c3c72b89a35b61dca01c

test:
  secret_key_base: fed0a90281e16bc65ffaaea26a347e933ad54d6718a66107aa8ff540520e2c9f3673c1f4fb68ad066208c5d5354d2ba8b09e7a52495b5feb6866a806b8e66556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
